"""Add hero settings

Revision ID: 62bdbb7e6e9d
Revises: 4c29c98f8ba3
Create Date: 2026-06-12 15:48:28.266769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bdbb7e6e9d'
down_revision = '4c29c98f8ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_text_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_cta_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_cta_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('hero_cta_link')
        batch_op.drop_column('hero_cta_text')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('hero_text_mode')

    # ### end Alembic commands ###
